### ISSUE TITLE
re: Nomad-intergration-with-Vault error trap step doesn't catch actions that don't not explicitly use pathing

### ISSUE THREAD

**Issue by joshua-bradley** [hashicorp/field-workshops-nomad#41]
ran the second step in this track [token creation](https://play.instruqt.com/hashicorp/tracks/nomad-integration-with-vault/challenges/create-the-nomad-server-policy-and-token/assignment) and solution check fails unless creation is done using the pathing (`/root/hashistack/vault`) contained inside instructions on the right-side panel.  See lab output below >

```shell
root@hashistack-server:~# vault policy write nomad-server hashistack/vault/nomad-server-policy.hcl
Success! Uploaded policy: nomad-server
root@hashistack-server:~# vault token create -policy nomad-server -period 72h -orphan > hashistack/nomad/nomad-token.txt
root@hashistack-server:~# cat hashistack/nomad/nomad-token.txt
Key                  Value
---                  -----
token                s.9UVziAXySv0mQZbytQn9ObmV
token_accessor       4KK0myIvcHnc6PCgElkgn8Mo
token_duration       72h
token_renewable      true
token_policies       ["default" "nomad-server"]
identity_policies    []
policies             ["default" "nomad-server"]
root@hashistack-server:~# cd /root/hashistack/vault
root@hashistack-server:~/hashistack/vault# cd
root@hashistack-server:~# vault policy list
default
nomad-server
root
```

error message >

![image](https://user-images.githubusercontent.com/20591398/78824417-29ffba00-7993-11ea-8529-07c6ac6dce08.png)

if user who is a relatively fast typer and understands pathing this would be frustrating as each step must be re-run with a copy/paste action

**Comment by lhaig** [comment]
@joshua-bradley Can we close this?

**Comment by rberlind** [comment]
@joshua-bradley : It sounds like things work correctly if user follows instructions.  I think the issue here is that the check expects this regex: `vault\s\+policy\s\+write\s\+nomad-server\s\+nomad-server-policy.hcl` in which `\s\+` stands for whitespace but you or an experienced user used `vault policy write nomad-server hashistack/vault/nomad-server-policy.hcl`. And that a similar problem exists for next command for which you used `vault token create -policy nomad-server -period 72h -orphan > hashistack/nomad/nomad-token.txt`.  Right?

While I could modify the check to also allow your alternative commands, these are not the only alternatives.  For instance, you could have done `vault policy write nomad-server /root/hashistack/vault/nomad-server-policy.hcl` for the first command.

I think there are too many commands that could have multiple alternatives to start modifying the scripts to catch all alternatives. 

I would prefer to close this without modifications.  But if you want to do a PR to make changes, I will review.  But if you do a PR, I think you should catch as many alternatives as possible and do it for all commands in the track or even across all of the Nomad workshop tracks.

**Comment by joshua-bradley** [comment]
thanks roger
